#!/bin/sh
homeDir=`echo $HOME`
logPath=$homeDir"/logs/ServerInstall.log"
#errorlog() { 

#   error=`cat $logPath | egrep "Unable|Invalid|Error" | wc -l`
#   if [ $error -ne 0 ]
#   then
#    echo "[Error while executing $1] .Please look into ServerInstall.log for details"
#  fi
# }



sudo touch $logPath
sudo chmod 777 $logPath
sudo mkdir -p $homeDir/logs/
sudo mkdir -p $homeDir/installer/shellscripts/trunk
sudo  mkdir -p $homeDir/userfiles
sudo chmod 777 $homeDir/logs/
sudo apt-get install python-paramiko --assume-yes 
sudo apt-get install subversion --assume-yes   
sudo apt-get install socat --assume-yes   
sudo apt-get install python-paramiko --assume-yes  
sudo apt-get install python-mysqldb --assume-yes   
sudo svn checkout https://github.com/boto/boto/trunk  

if [ -e "$homeDir/installer/shellscripts/trunk" ]
then
   cd $homeDir/installer/shellscripts/trunk
   sudo python $homeDir/installer/shellscripts/trunk/setup.py install
else
   echo "[Error] $homeDir/installer/shellscripts/trunk path does not exists" >> $logPath
fi

if [ -e "$homeDir/installer/key/anand2.key" ]
then
    sudo chmod 600 $homeDir/installer/key/anand2.key
else
   echo "[Error] $homeDir/installer/pythonscripts/akg.pem does not exists" >> $logPath
fi

  sudo apt-get update --assume-yes >> $logPath 2>&1                ### Executing Update
  #errorlog "apt-get update"
  
  sudo apt-get install php5 --assume-yes >> $logPath 2>&1        ### Installing PHP5
  #errorlog "apt-get install php5" 
  
  sudo apt-get install php5-mysql  --assume-yes >> $logPath 2>&1  ### Installing Php5-mysql
  #errorlog "apt-get install php5-mysql"
  
  sudo dpkg-reconfigure php5-mysql   >> $logPath 2>&1             ### depkging 
  #errorlog "dpkg-reconfiguree php5-mysql"
  
  sudo chmod 777 /etc/apt/sources.list                                   
  sudo sed 's/$/ multiversal/g' /etc/apt/sources.list > sources.list_temp   ### Editing sources.list. Adding multiversal
  sudo sed 's/^ multiversal$//g' sources.list_temp > /etc/apt/sources.list 
  sudo chmod 644 /etc/apt/sources.list       ### Restoring the file permission

  line=`grep "www-data  ALL=(ALL) NOPASSWD:ALL" /etc/sudoers | wc -l`
  if [ $line -eq 0 ]
  then 
  echo "www-data  ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
  fi

  if [ -e "$homeDir/installer" ]
  then
  sudo chmod -R 777 $homeDir/installer
  sudo chown -R www-data:www-data $homeDir/installer
  else
   echo "[Error]: $homeDir/installer does not exists" >> $logPath
  fi

   sqlFile="$homeDir/userfiles/tables.sql"
   sudo chmod 777 $sqlFile
   dataFile="$homeDir/userfiles/data.sql"
   sudo chmod 777 $dataFile
  
  export DEBIAN_FRONTEND=noninteractive
  echo "################################### apt-get update  ###############################################" >>$logPath 2>&1
    sudo  DEBIAN_FRONTEND=noninteractive apt-get update --assume-yes >>$logPath 2>&1
  #errorlog "update "
    export DEBIAN_FRONTEND=noninteractive
  echo "##################################### mysql-server #############################################"  >>$logPath 2>&1
    sudo DEBIAN_FRONTEND=noninteractive apt-get -q -y install mysql-server-5.1 --assume-yes >>$logPath 2>&1 ### installing mysql server
  #errorlog "mysql-server-5.1"
    echo "####################################### mysql-client ###########################################"  >>$logPath 2>&1
  sudo  DEBIAN_FRONTEND=noninteractive apt-get install mysql-client-5.1 --assume-yes >>$logPath 2>&1 ### install mysql client
    #errorlog "mysql-client-5.1"
  echo "######################################## phpmyadmin ##########################################" >>$logPath 2>&1
    export DEBIAN_FRONTEND=noninteractive
  sudo DEBIAN_FRONTEND=noninteractive apt-get -q -y install phpmyadmin  --assume-yes >>$logPath 2>&1  ### installing phpmyadmin
    echo "####################################### apache2 ###########################################" >>$logPath 2>&1
  #errorlog "phpmyadmin"
    sudo apt-get install apache2 --assume-yes  >>$logPath 2>&1  ####installing apache2
  echo "##################################################################################" >>$logPath 2>&1
    #errorlog "apache2"

   echo "#################################### editing apache2.conf ##############################################" >>$logPath 2>&1
    sudo chmod 777 /etc/apache2/apache2.conf
    sudo  echo "Include /etc/phpmyadmin/apache.conf" >> /etc/apache2/apache2.conf  ### Updating apache2.conf to include phpmyadmin details
    sudo chmod 644 /etc/apache2/apache2.conf

   echo "#################################### editing my.cnf ##############################################" >>$logPath 2>&1
    sudo chmod 777 /etc/mysql/my.cnf
    sed -e "s#bind-address#\#bind-address#g" /etc/mysql/my.cnf  > tmp                      ### Updating my.cnf to accept connection from all server
    sed -e "s#skip-external-locking#\#skip-external-locking#g" tmp > /etc/mysql/my.cnf
    rm tmp
    sudo chmod 644 /etc/mysql/my.cnf
   echo "######################################## restarting service ##########################################" >>$logPath 2>&1
    sudo /etc/init.d/apache2 restart >>$logPath 2>&1  ### restarting apache2
    sudo /etc/init.d/mysql restart   >>$logPath 2>&1  ### restarting mysql
    mysqladmin -u root password root             ### setting password to root
   echo "################################### privileges ###############################################" >>$logPath 2>&1
   mysql -uroot -hlocalhost -proot  -e "grant all privileges on *.* to  'root'@'%' identified by 'root';"  ####Granting all privilege to root

   if [ -e $sqlFile ]
   then
   sudo chmod 777 $sqlFile
   mysql -uroot -hlocalhost -proot <  $sqlFile
   else
     echo "[Error] $sqlFile is not present" >> $logPath
   fi
   if [ -e $dataFile ]
   then
   sudo chmod 777 $dataFile
   mysql -uroot -hlocalhost -proot < $dataFile
   else
    echo "[Info] $dataFile is not present" >> $logPath
   fi



   ######################   PHP Stuff##############################################################
   sudo cp -r $homeDir/userfiles/* /var/www/
   sudo touch /var/www/python.log
   sudo chmod 777 /var/www/*
   
   sudo touch $homeDir/installer/shellscripts/instances.dat
   sudo chmod 777 $homeDir/installer/shellscripts/instances.dat
   sudo echo "mysql=localhost" > $homeDir/installer/shellscripts/instances.dat
  sudo rm /var/www/index.html  ### removing the default index.html
  sudo mkdir /var/www/files  #### creating /var/www/files to store the user scripts
 
  if [ -e "$homeDir/installer/shellscripts/deployScript" ]
  then
  sudo $homeDir/installer/shellscripts/deployScript $homeDir/userfiles/ServerScripts.tar /var/www/   ### Copying scripts in /var/www
  else
    echo "[Error] $homeDir/installer/shellscripts/deployScript is missing" >> $logPath
  fi

  if [ -e "$homeDir/installer/shellscripts/updateConfig" ]
  then
  sudo $homeDir/installer/shellscripts/updateConfig /var/www/dbconfig.php  $homeDir/installer/shellscripts/instances.dat ###updating dbconfig.php with database private ip
  else
    echo "[Error] $homeDir/installer/shellscripts/updateConfig is missing" >> $logPath
  fi
 
  sudo chmod 777 /var/www
  sudo chmod 777 /var/www/*    ### setting 777 in /var/www

  sudo /etc/init.d/apache2 restart   >> $logPath 2>&1   ### Restarting apache

  sudo rm $homeDir/installer/shellscripts/instances.dat

