#!/bin/sh

if [ $# -eq 0 ]
then
  echo "Enter the hostname"
  exit
fi

hostname=$1

if [ $# -eq 2 ]
then
  key=$2
  ssh -i $key "ubuntu@"$hostname
else
  ssh -i ~/Desktop/ag2key.pem "ubuntu@"$hostname
fi


