#!/bin/sh
logPath="/home/ubuntu/haproxyinstall.log"
errorlog() {

   error=`cat $logPath | egrep "Unable|Invalid|Error" | wc -l`
   if [ $error -ne 0 ]
   then
    echo "[Error while executing $1] .Please look into $logPath for details"
  fi
 }

 if [ -e "/etc/haproxy/haproxy.cfg" ]
 then
    isInstalled=1
 else
    isInstalled=0
 fi
echo $isInstalled

 if [ $isInstalled -eq 0 ]
 then
  sudo apt-get update --assume-yes >$logPath 2>&1                ### Executing Update
  errorlog "apt-get update"
  sudo apt-get install haproxy --assume-yes >>$logPath 2>&1        ### Installing haproxy
  errorlog "apt-get install haproxy" 
  sudo chmod 777  /etc/apt/sources.list
  sed 's/$/ multiversal/g' /etc/apt/sources.list > sources.list_temp   ### Editing sources.list adding multiversal
  sed 's/^ multiversal$//g' sources.list_temp > /etc/apt/sources.list 
  sudo chmod 644 /etc/apt/sources.list
 else
  perl /home/ubuntu/installer/shellscripts/haProxyConfig  ### Preparing content for haproxy.cfg file
 fi
  sudo chmod 777 /home/ubuntu/installer/shellscripts/instances.dat
  sudo chmod 777 /etc/haproxy/haproxy.cfg
  sudo cp /etc/haproxy/haproxy.cfg  /etc/haproxy/haproxy.cfg_bk
  sudo cat /home/ubuntu/installer/shellscripts/haproxy.cfg  > /etc/haproxy/haproxy.cfg
  sudo chmod 644 /etc/haproxy/haproxy.cfg
  #sudo haproxy -f /etc/haproxy/haproxy.cfg >>$logPath 2>&1
  #sudo  haproxy -V -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf >>$logPath 2>&1
  sudo haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf $(cat  /var/run/haproxy.pid)
  error=`cat $logPath | egrep "Unable|Invalid|Error" | wc -l`
  if [ $error -eq 0 ]
  then
    echo "Load Balancer webserver has been installed successfully"
  fi

