#!/bin/sh
homeDir="/root"
logPath=$homeDir"/logs/mysqlinstall.log"
#errorlog() {
#   error=`cat $logPath | egrep "Unable|Invalid|Error" | wc -l`
#   if [ $error -ne 0 ]
#   then
#    echo "[Error while executing $1] .Please look into $logPath for details"
#  fi
# }

sqlFile="$homeDir/userfiles/"$1"/customer.sql"
#sudo chmod 777 $sqlFile
dataFile="$homeDir/userfiles/"$1"/data.sql"
#sudo chmod 777 $dataFile
  sudo $homeDir/installer/shellscripts/prepareinstance.sh    
  export DEBIAN_FRONTEND=noninteractive
  echo "################################### apt-get update  ###############################################" >>$logPath 2>&1
    sudo  DEBIAN_FRONTEND=noninteractive apt-get update --assume-yes >$logPath 2>&1
  #errorlog "update "
    export DEBIAN_FRONTEND=noninteractive
  echo "##################################### mysql-server #############################################"  >>$logPath 2>&1
    sudo DEBIAN_FRONTEND=noninteractive apt-get -q -y install mysql-server-5.1 --assume-yes >>$logPath 2>&1 ### installing mysql server
  #errorlog "mysql-server-5.1"
    echo "####################################### mysql-client ###########################################"  >>$logPath 2>&1
  sudo  DEBIAN_FRONTEND=noninteractive apt-get install mysql-client-5.1 --assume-yes >>$logPath 2>&1 ### install mysql client
    #errorlog "mysql-client-5.1"
  echo "######################################## phpmyadmin ##########################################" >>$logPath 2>&1
    export DEBIAN_FRONTEND=noninteractive
  sudo DEBIAN_FRONTEND=noninteractive apt-get -q -y install phpmyadmin  --assume-yes >>$logPath 2>&1  ### installing phpmyadmin
    echo "####################################### apache2 ###########################################" >>$logPath 2>&1
  #errorlog "phpmyadmin"
    sudo apt-get install apache2 --assume-yes  >>$logPath 2>&1  ####installing apache2
  echo "##################################################################################" >>$logPath 2>&1
    #errorlog "apache2"

  
   echo "#################################### editing apache2.conf ##############################################" >>$logPath 2>&1
    sudo chmod 777 /etc/apache2/apache2.conf
    sudo  echo "Include /etc/phpmyadmin/apache.conf" >> /etc/apache2/apache2.conf  ### Updating apache2.conf to include phpmyadmin details
    sudo chmod 644 /etc/apache2/apache2.conf

   echo "#################################### editing my.cnf ##############################################" >>$logPath 2>&1
    sudo chmod 777 /etc/mysql/my.cnf
    sed -e "s#bind-address#\#bind-address#g" /etc/mysql/my.cnf  > tmp                      ### Updating my.cnf to accept connection from all server
    sed -e "s#skip-external-locking#\#skip-external-locking#g" tmp > /etc/mysql/my.cnf
    rm tmp
    sudo chmod 644 /etc/mysql/my.cnf
   echo "######################################## restarting service ##########################################" >>$logPath 2>&1
    sudo /etc/init.d/apache2 restart >>$logPath 2>&1  ### restarting apache2
    sudo /etc/init.d/mysql restart   >>$logPath 2>&1  ### restarting mysql
    mysqladmin -u root password root             ### setting password to root
   echo "################################### privileges ###############################################" >>$logPath 2>&1
   mysql -uroot -hlocalhost -proot  -e "grant all privileges on *.* to  'root'@'%' identified by 'root';"  ####Granting all privilege to root

   if [ -e $sqlFile ]
   then
   sudo chmod 777 $sqlFile
   mysql -uroot -hlocalhost -proot <  $sqlFile
   fi
   if [ -e $dataFile ]
   then
   sudo chmod 777 $dataFile
   mysql -uroot -hlocalhost -proot < $dataFile
   fi
   

